### ISSUE TITLE
Read from IdentifiedElementsList crashes if the index is negative

### ISSUE THREAD

**Issue by karol-arndt** [antmicro/Migrant#113]
Negative index value can happen when the file is malformed. In that case, a more descriptive explanation should be presented (currently it throws an IndexOutOfRange exception).

**Comment by mateusz-holenko** [comment]
To keep code as readable as possible we decided not to implement sanity checks everywhere. The desired behavior is to crash deserialization with original exception and catch it in `TryDeserialize` method. If `Deserialize` method is called then the original exception is re-thrown.
