### ISSUE TITLE
Cannot deserialize AttributeCollection instances

### ISSUE THREAD

**Issue by rebulanyum** [antmicro/Migrant#114]
Hello.

Suppose I have 2 processes (applications). Process (A) is serializing CRM Entity objects into a file. Process (B) is reading the file and deserializing them into CRM Entity objects. The CRM Entity object is the instance of Microsoft.Xrm.Sdk.Entity type. We're doing this for a kind of a custom import tool for our clients: think of Process (A) as application that is used by The Software Company and Process (B) as application that is used by Customers. And the file is interchaning between The Software Company and Customers.

So, things are working pretty well; even with multiple customers in our case it's fine. However, we encountered a problem: Every customer may have it's own Microsoft Dynamics CRM SDK library: Meaning, every customer will have it's own Microsoft.Xrm.Sdk assembly version. For example The Software Company will use SDK 2016 (file version: 8.0.1.139, assembly version: 8.0.0.0), Customer1 will use SDK 2016 (file version: 8.0.0.89, assembly version: 8.0.0.0), Customer2 will use SDK 2015 (file version: 7.0.0.39, assembly version: 7.0.0.0) etc. The deserialization process fails for both of the customers at this point. That means The software company have to deserialize in a special way for every Customer one by one and ask for their versions. That's not easy :) And it's a bug also.

I tried the following settings for both serializing and deserializing but it didn't work: 
`new Settings(versionTolerance: VersionToleranceLevel.AllowGuidChange | VersionToleranceLevel.AllowFieldAddition | VersionToleranceLevel.AllowFieldRemoval | VersionToleranceLevel.AllowAssemblyVersionChange)`.
This causes the exception to be thrown on the customer: `Field _innerDictionary type changed in class Microsoft.Xrm.Sdk.DataCollection`2.`.

The only way I can achieve this is by disabling the type stamping feature like this:
`new Settings(versionTolerance: VersionToleranceLevel.AllowGuidChange | VersionToleranceLevel.AllowFieldAddition | VersionToleranceLevel.AllowFieldRemoval | VersionToleranceLevel.AllowAssemblyVersionChange, disableTypeStamping: true)`

Questions:
1- What is the type stamping for real? I looked down the code and realized that it's just an option between FullTypeDescriptor & SimpleTypeDescriptor. So, what's the difference? Advantages, disadvantages? And disabling the type stamp feature is the real solution in my case?

2- In the default scenerio (`disableTypeStamping: false` & different file versions between parties) Entity.Attributes collection cannot be deserialized because of the field `private AttributeCollection _attributes;`. Because AttributeCollection class inherits `DataCollection<string, object>` class that has the field `private IDictionary<TKey, TValue> _innerDictionary = new Dictionary<TKey, TValue>();` which causes the exception on deserialization process. Can you please check and/or fix it please?

(Can't contribute since your code is kind of hard to understand; but only if you have a guide/document for it! I mean too much of TypeDescriptors and casting...)

And thank you for the effort on the Migrant Library.

**Comment by mateusz-holenko** [comment]
Hi!

I just wanted to let you know that a fix for the issue with `Field _innerDictionary type changed in class Microsoft.Xrm.Sdk.DataCollection2.` has been just merged to master.

Regarding your question about type stamping: it's a mechanism for writing class metadata to a stream (next to the actual data) in order to detect and properly handle changes in type structure (e.g., adding a new field, changing a type of a field, etc.). The main disadvantage of it is an increase in the size of serialized data.
