### ISSUE TITLE
Cannot serialize DataTable

### ISSUE THREAD

**Issue by fnicollier** [antmicro/Migrant#79]
When I attempt to serialize a DataTable, it fails with the following exception:

>System.InvalidOperationException : Pointer or ThreadLocal encountered during serialization. The classes path that lead to it was: DataTable => CultureInfo => CompareInfo

Edit: If I set supportForISerializable to True it works. Would still be nice for a custom DataTable writer/reader.

**Comment by konrad-kruczynski** [comment]
Hi,
regarding the `CultureInfo`: we will probably soon introduce built in surrogate that will deal with it. However 'DataTable' is a big structure and also domain specific - in the sense that it will only be seen in some applications. Moreover, `DataTable` is quite a complex structure. So - we can probably support a surrogate for `Data*` things (which will be located in a migrant contributions repository - yet to be created), but you'd have to do the surrogate yourself - no free human resources at this moment ;) So, what's your opinion?

**Comment by fnicollier** [comment]
I'll be happy to do the surrogate.

**Comment by konrad-kruczynski** [comment]
What's the status?

**Comment by fnicollier** [comment]
Hi, after some comparisons I ended up going with Protobuf instead.
