### ISSUE TITLE
What does "Multimoduled assemblies are not supported" mean?

### ISSUE THREAD

**Issue by rogeralsing** [antmicro/Migrant#88]
We got an issue reported over here: https://github.com/akkadotnet/akka.net/pull/1232#issuecomment-129851884

That when running our framework with Migrant as the default message serializer, then there is an "Multimoduled assemblies are not supported" exception thrown when consuming the whole thing from the F# built in REPL. (Edgecase I know, F# and only in REPL mode only)

What is the cause of this message and is there anything that we can do to deal with it?

**Comment by mateusz-holenko** [comment]
Up to this moment we did not encountered assemblies having more than one module. As a result we considered them to be non-typical for `C#` language and did not provide support for them.

I will look into the subject and evaluate the complexity of introducing this support to `Migrant`.

**Comment by rogeralsing** [comment]
Akka.NET users are excited to see the changes in Migrant for this issue :)
Thanks for the quick fix!

![fsi](https://cloud.githubusercontent.com/assets/647031/9219823/f24f23ae-40dd-11e5-90f1-dd8d5fd1627d.png)

**Comment by konrad-kruczynski** [comment]
Hi guys.
The fix has just been merged into master. It should resolve your problems. Note, however, that it changes the protocol so that data serialized with previous version (i.e. one before fix) will not be deserializable with the current one. If it works for you, please close the issue.

**Comment by konrad-kruczynski** [comment]
Closing.
