### ISSUE TITLE
ObjectWriter writer method cache

### ISSUE THREAD

**Issue by rogeralsing** [antmicro/Migrant#94]
It seems like writer methods are cached per `ObjectWriter` instance.
This means that each call to `Serialize` will have to rebuild the writer method cache, even if the same serializer instance is used.

```csharp
        public void Serialize(object obj, Stream stream)
        {
            WriteHeader(stream);
            using(var writer = ObtainWriter(stream)) //new writerand thus new writer method cache
            {
                writer.WriteObject(obj);
            }
            serializationDone = true;
        }
```

Would it be possible to cache the writer methods per serializer instance instead of per object writer, as the serializer settings should not change during its lifetime and this writer methods should be safe to re-use between individual serialization calls.

To me it looks like it should be possible, but I have far too little context here.

**Comment by konrad-kruczynski** [comment]
The write method cache is preserved between calls to Serialize - look at the `ObtainWriter` code:
```csharp
var writer = new ObjectWriter(stream, OnPreSerialization, OnPostSerialization, 
                             writeMethodCache, surrogatesForObjects, settings.SerializationMethod == Method.Generated, 
                             settings.TreatCollectionAsUserObject, settings.UseBuffering, settings.ReferencePreservation);
return writer;
```

The `writeMethodCache` is a `Serializer`'s field.

**Comment by rogeralsing** [comment]
![migrantperf2](https://cloud.githubusercontent.com/assets/647031/9300031/32f3065e-44c2-11e5-8bcc-24314bd0c6c3.png)

This profiling session is from running 1 mil iterations serializing the same type. `CreateDelegate` is definitely not being cached here.

**Comment by konrad-kruczynski** [comment]
Yes, this is because *methods* are cached, but not delegates. This delegate also contains an object writer instance which holds some data like instance ids. If `CreateDelegate` call is expensive (as one can see from the profiler report), then maybe such object should be a parameter of this delegate.

**Comment by konrad-kruczynski** [comment]
Hi Roger,
I have just commited the change to master. Please look whether it improves performance in your scenario.
