### ISSUE TITLE
Design and implement API for generic surrogates

### ISSUE THREAD

**Issue by mateusz-holenko** [antmicro/Migrant#95]
Right now we are unable to install single surrogate for generic type which renders simple surrogation of types like `List<T>`, `Tuple<T1, T2>`, etc., impossible.

Due to a limitation of *C#* syntax we cannot pass open generic type as an argument to `ForObject` and `ForSurrogate` methods, like: `ForObject<List<>>(...)` or `ForObject<List<T>>(...)`, so we must think of a new API.

**Comment by konrad-kruczynski** [comment]
Done.
